module.exports = {
  EOF: -1,
  ID: -2,
  NUM: -3,
  ASSIGN_OP: -4,
  COMPARISON_OP: -5,
  ADD_OP: -6,
  SUB_OP: -7,
  MULT_OP: -8,
  DIV_OP: -9,
  LEFT_PAREN: -10,
  RIGHT_PAREN: -11,
  LEFT_BRACKET: -12,
  RIGHT_BRACKET: -13,
  COMMA: -14,
  NEWLINE: -15,
  FUNCTION_KEYWORD: -16,
  END_KEYWORD: -17
}
